export const tecsList = [
  {
    concepts: [
      ['Aprendizado Contínuo', 'Continuous Learning'],
      ['Pensamento Analítico', 'Analytical Thinking'],
      ['Versionamento de Código', 'Code versioning'],
      ['Orientação a Objeto', 'Object Orientation'],
      ['"Mobile First"', 'Mobile First'],
      ['Código Limpo', 'Clean Code'],
      ['Acessibilidade', 'Accessibility'],
      ['Arquitetura de software', 'Software Architecture'],
      ['Arquitetura de Informação', 'Information Architecture'],
      ['Programação Funcional', 'Functional Programming'],
      ['Experiência e Interface do Usuário', 'User Experience and Interface'],
      ['Gerenciamento de estado', 'State Management'],
      ['Renderização no servidor', 'Server Side Render'],
      ['Banco de Dados Relacional', 'Relational Database'],
      ['Segurança da Informação', 'Information Security'],
      ['Trabalho em Equipe', 'Teamwork'],
      ['Autogestão', 'Self-Management'],
      ['Desenvolvimento Ágil', 'Agile Development'],
    ],
  },
  {
    programs: [
      'Git / Github',
      'Visual Studio Code',
      'Figma',
      'Sony Vegas',
      'Microsoft 365',
      'Premiere Pro',
      'Cisco Packet Tracer',
      'Adobe Lightroom',
      'PostgreSQL',
      'PgAdmin4',
      'Docker',
      'Notion',
      'Photoshop',
      'Wordpress',
      'Adobe XD',
      'Adobe Dreamweaver',
      'Adobe Dimension 3D',
    ]
  },
  {
    tecsSrc: [
      'img-javascript.png',
      'img-react.png',
      'img-typescript.png',
      'img-tailwind.png',
      'img-nextjs.png',
      'img-bootstrap.png',
      'img-jquery.png',
      'img-github.png',
      'img-figma.png',
      'img-uiux.png',
      'img-styledcomponents.png',
      'img-sass.png',
      'img-html.png',
      'img-css.png',
      'img-visualcode.png',
      'img-photoshop.png',
      'img-lightroom.png',
      'img-microsoft365.png',
      // 'img-postgres.png',
      // 'img-docker.png',
      // 'img-pgadmin.png',
      // 'img-wordpress.png',
      // 'img-adobe.png',
      // 'img-xd.png',
      // 'img-dreamweaver.png',
      // 'img-dimension.png',
    ],
  },
];